[project]
name = "mlstatus"
version = "0.1.0"
description = "Display status bar while your machine learning script runs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "python-lsp-ruff>=2.2.2",
]
